# @Author : 墨宣
# @Time : 2022/1/1 16:52
# @File : 2.py
# 目的 :
print(3 % -2)
print(3 // 2)
print(3 ** 2)
python = int(input("请输入python成绩:"))
c = int(input("请输入c成绩:"))
java = int(input("请输入Java成绩:"))
print("Python与c的成绩差:", abs(python - c))
a = int(input())
b = int(input())
print("a&b=", a & b)
print("a|b=", a | b)
print("a^b=", a ^ b)
print("~a=", ~a)
print("~b=", ~b)
print("a向左移b位后的结果:", a << b)
print("b向左移a位后的结果:", b << a)
print("a向右移b位后的结果", a >> b)
print("b向右移a位后的结果", b >> a)
print("a>b") if (a > b) else print("a<b")
sum = float(input("请输入所加油的总金额:"))
l = float(input("请输入加油后运行的公里数:"))
print("油耗:", (sum / 6.27) / l)
