bicycles=['treck','cannondale','redline','spec']
print(bicycles)
print(bicycles[0])
bicycles[0]='aisi'
print(bicycles)
bicycles.append('lufei')
print(bicycles)
bicycles.insert(0,'suolong')
print(bicycles)
del bicycles[2]
print(bicycles)
bicycles.pop()
print(bicycles)
bicycles.remove('spec')
print(bicycles)
bicycles.sort()
print(bicycles)
bicycles.sort(reverse=True)
print(bicycles)
print(sorted(bicycles))
print(sorted(bicycles,reverse=True))
bicycles.reverse()
print(bicycles)
print(len(bicycles))
#总结：
#1.append函数：
#在列表末尾添加元素格式为xxx.append（'yyy'）。yyy为添加的元素；
#2.insert函数：
#在列表里添加元素，格式为xxx.insert（n,'yyy').n为想插入的元素在列表中的位置，’yyy‘为插入的元素。
#3.del函数：
#删除列表里的元素，格式为del xxx[n],n为想要删除的元素在列表中的位置。
#4.pop函数：
#删除列表末尾的元素，格式为xxx.pop()。
#5.remove函数:
#删除列表中的元素，格式为xxx.remove('yyy')。yyy为想要删除的元素。
#6.sort函数：
#永久地改变列表中元素的排列顺序，按照首字母从小到大的顺序。格式为xxx.sort()。如果想要使排列顺序相反，则xxx.sort(reverse=True)。
#7.sorted函数：
#暂时的改变列表中元素的排列顺序。格式为print(sorted(xxx))。如果想要使排列顺序相反，则为print(sorted(xxx,reverse=True))。因为sorted函数的结果是暂时的，所以需要与print语句一起。
#8.reverse函数：反转列表中的元素。
#9.len函数：
#确定列表的长度。格式为print(len(xxx))。